<template>
    <div class="xmSort">
        <sort-header></sort-header>
        <sort-body :proDatas="data"></sort-body>
        <sort-footer></sort-footer>
    </div>
</template>

<script>
    import SortHeader from '../components/xmSort/SortHeader'
    import SortBody from '../components/xmSort/SortBody'
    import SortFooter from '../components/xmCommonn/Footer'
    export default {
        data(){
            return{
                data:[
                        {
                            "id":1,
                            "name":"新品",
                            "pic":"../../../static/img/item1.jpg",
                            "item":[
                                {
                                    "itemName":"手机",
                                    "product":[
                                        {
                                            "pro":"小米8","shows":"../../../static/img/itemLi11-11.png"
                                        },
                                        {
                                            "pro":"小米8 SE","shows":"../../../static/img/itemLi11-12.png"
                                        },
                                        {
                                            "pro":"小米MIX 2S","shows":"../../../static/img/itemLi11-13.png"
                                        },
                                        {
                                            "pro":"红米S2","shows":"../../../static/img/itemLi11-14.png"
                                        },
                                        {
                                            "pro":"红米6 Pro","shows":"../../../static/img/itemLi11-15.png"
                                        },
                                        {
                                            "pro":"红米6","shows":"../../../static/img/itemLi11-16.png"
                                        },
                                        {
                                            "pro":"红米6A","shows":"../../../static/img/itemLi11-17.png"
                                        }
                                    ],
                                },
                                {
                                    "itemName":"电视",
                                    "product":[
                                        {
                                            "pro":"75英寸 电视4","shows":"../../../static/img/itemLi12-11.png"
                                        },
                                        {
                                            "pro":"55英寸4S 曲面","shows":"../../../static/img/itemLi12-11.png"
                                        },
                                        {
                                            "pro":"55英寸 4X","shows":"../../../static/img/itemLi12-11.png"
                                        },
                                        {
                                            "pro":"32英寸 4C","shows":"../../../static/img/itemLi12-11.png"
                                        },
                                        {
                                            "pro":"43英寸 4S","shows":"../../../static/img/itemLi12-11.png"
                                        },
                                        {
                                            "pro":"43英寸 青春版","shows":"../../../static/img/itemLi12-11.png"
                                        },
                                        {
                                            "pro":"红米6A","shows":"../../../static/img/itemLi12-11.png"
                                        }
                                    ],
                                },
                                {
                                    "itemName":"电脑",
                                    "product":[
                                        {
                                            "pro":"15.6”游戏本","shows":"../../../static/img/itemLi13-11.png"
                                        },
                                        {
                                            "pro":"13.3”增强版","shows":"../../../static/img/itemLi13-11.png"
                                        },
                                        {
                                            "pro":"12.5”office版","shows":"../../../static/img/itemLi13-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":2,
                            "name":"手机",
                            "pic":"../../../static/img/item2.jpg",
                            "item":[
                                {
                                    "itemName":"小米手机",
                                    "product":[
                                        {
                                            "pro":"小米8","shows":"../../../static/img/itemLi21-11.png"
                                        },
                                        {
                                            "pro":"小米8 SE","shows":"../../../static/img/itemLi21-12.png"
                                        },
                                        {
                                            "pro":"小米MIX 2S","shows":"../../../static/img/itemLi21-13.png"
                                        },
                                        {
                                            "pro":"小米6X","shows":"../../../static/img/itemLi21-11.png"
                                        },
                                        {
                                            "pro":"黑鲨游戏手机","shows":"../../../static/img/itemLi21-11.png"
                                        },
                                        {
                                            "pro":"小米MIX 2","shows":"../../../static/img/itemLi21-11.png"
                                        },
                                        {
                                            "pro":"小米Max 2","shows":"../../../static/img/itemLi21-11.png"
                                        }
                                    ],
                                    
                                },
                                {
                                    "itemName":"红米手机",
                                    "product":[
                                        {
                                            "pro":"红米6 Pro","shows":"../../../static/img/itemLi22-11.png"
                                        },
                                        {
                                            "pro":"红米6","shows":"../../../static/img/itemLi22-11.png"
                                        },
                                        {
                                            "pro":"红米6A","shows":"../../../static/img/itemLi22-11.png"
                                        },
                                        {
                                            "pro":"红米Note 5","shows":"../../../static/img/itemLi22-11.png"
                                        },
                                        {
                                            "pro":"红米S2","shows":"../../../static/img/itemLi22-11.png"
                                        },
                                        {
                                            "pro":"红米5","shows":"../../../static/img/itemLi22-11.png"
                                        },
                                        {
                                            "pro":"红米5 Plus","shows":"../../../static/img/itemLi22-11.png"
                                        },
                                        {
                                            "pro":"红米5A","shows":"../../../static/img/itemLi22-11.png"
                                        }
                                    ]
                                },
                                {
                                    "itemName":"移动4G+专区",
                                    "product":[
                                        {
                                            "pro":"红米6","shows":"../../../static/img/itemLi23-11.png"
                                        },
                                        {
                                            "pro":"红米6A","shows":"../../../static/img/itemLi23-11.png"
                                        },
                                        {
                                            "pro":"小米MIX 2S","shows":"../../../static/img/itemLi23-11.png"
                                        },
                                        {
                                            "pro":"红米Note 5","shows":"../../../static/img/itemLi23-11.png"
                                        },
                                        {
                                            "pro":"红米5 Plus","shows":"../../../static/img/itemLi23-11.png"
                                        }
                                    ],
                                    "botPic":"../../../static/img/item_more2.jpg"
                                },
                                {
                                    "itemName":"手机配件",
                                    "product":[
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        },
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        },
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        },
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        },
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        },
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        },
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        },
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        },
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        },
                                        {
                                            "pro":"以旧换新","shows":"../../../static/img/itemLi24-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":3,
                            "name":"电视",
                            "pic":"../../../static/img/item3.jpg",
                            "item":[
                                {
                                    "itemName":"移动4G",
                                    "product":[
                                        {
                                            "pro":"32-40英寸","shows":"../../../static/img/itemLi31-11.png"
                                        },
                                        {
                                            "pro":"32-40英寸","shows":"../../../static/img/itemLi31-11.png"
                                        },
                                        {
                                            "pro":"32-40英寸","shows":"../../../static/img/itemLi31-11.png"
                                        },
                                        {
                                            "pro":"32-40英寸","shows":"../../../static/img/itemLi31-11.png"
                                        },
                                        {
                                            "pro":"32-40英寸","shows":"../../../static/img/itemLi31-11.png"
                                        },
                                        {
                                            "pro":"32-40英寸","shows":"../../../static/img/itemLi31-11.png"
                                        }
                                    ],
                                    "botPic":"../../../static/img/item_more3.jpg"
                                },
                                {
                                    "itemName":"盒子",
                                    "product":[
                                        {
                                            "pro":"盒子4","shows":"../../../static/img/itemLi32-11.png"
                                        },
                                        {
                                            "pro":"盒子4","shows":"../../../static/img/itemLi32-11.png"
                                        },
                                        {
                                            "pro":"盒子4","shows":"../../../static/img/itemLi32-11.png"
                                        },
                                        {
                                            "pro":"盒子4","shows":"../../../static/img/itemLi32-11.png"
                                        },
                                        {
                                            "pro":"盒子4","shows":"../../../static/img/itemLi32-11.png"
                                        }
                                    ],
                                },
                                {
                                    "itemName":"电视配件与会员",
                                    "product":[
                                        {
                                            "pro":"会员卡","shows":"../../../static/img/itemLi33-11.png"
                                        },
                                        {
                                            "pro":"会员卡","shows":"../../../static/img/itemLi33-11.png"
                                        },
                                        {
                                            "pro":"会员卡","shows":"../../../static/img/itemLi33-11.png"
                                        },
                                        {
                                            "pro":"会员卡","shows":"../../../static/img/itemLi33-11.png"
                                        },
                                        {
                                            "pro":"会员卡","shows":"../../../static/img/itemLi33-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":4,
                            "name":"电脑",
                            "pic":"../../../static/img/item4.jpg",
                            "item":[
                                {
                                    "itemName":"电脑",
                                    "product":[
                                        {
                                            "pro":"平板","shows":"../../../static/img/itemLi41-11.png"
                                        },
                                        {
                                            "pro":"平板","shows":"../../../static/img/itemLi41-11.png"
                                        },
                                        {
                                            "pro":"平板","shows":"../../../static/img/itemLi41-11.png"
                                        },
                                        {
                                            "pro":"平板","shows":"../../../static/img/itemLi41-11.png"
                                        },
                                        {
                                            "pro":"平板","shows":"../../../static/img/itemLi41-11.png"
                                        },
                                    ],
                                    "borPic":"../../../static/img/item_more4.jpg"
                                },
                                {
                                    "itemName":"电脑配件",
                                    "product":[
                                        {
                                            "pro":"鼠标/鼠标垫","shows":"../../../static/img/itemLi42-11.png"
                                        },
                                        {
                                            "pro":"鼠标/鼠标垫","shows":"../../../static/img/itemLi42-11.png"
                                        },
                                        {
                                            "pro":"鼠标/鼠标垫","shows":"../../../static/img/itemLi42-11.png"
                                        },
                                        {
                                            "pro":"鼠标/鼠标垫","shows":"../../../static/img/itemLi42-11.png"
                                        },
                                        {
                                            "pro":"鼠标/鼠标垫","shows":"../../../static/img/itemLi42-11.png"
                                        },
                                        {
                                            "pro":"鼠标/鼠标垫","shows":"../../../static/img/itemLi42-11.png"
                                        },
                                        {
                                            "pro":"鼠标/鼠标垫","shows":"../../../static/img/itemLi42-11.png"
                                        },
                                        {
                                            "pro":"鼠标/鼠标垫","shows":"../../../static/img/itemLi42-11.png"
                                        }
                                    
                                    ],
                                }
                            ]
                        },
                        {
                            "id":5,
                            "name":"家电",
                            "pic":"../../../static/img/item2.jpg",
                            "item":[
                                {
                                    "itemName":"家电",
                                    "product":[
                                        {
                                            "pro":"电饭煲","shows":"../../../static/img/itemLi51-11.png"
                                        },
                                        {
                                            "pro":"电饭煲","shows":"../../../static/img/itemLi51-11.png"
                                        },
                                        {
                                            "pro":"电饭煲","shows":"../../../static/img/itemLi51-11.png"
                                        },
                                        {
                                            "pro":"电饭煲","shows":"../../../static/img/itemLi51-11.png"
                                        },
                                        {
                                            "pro":"电饭煲","shows":"../../../static/img/itemLi51-11.png"
                                        },
                                        {
                                            "pro":"电饭煲","shows":"../../../static/img/itemLi51-11.png"
                                        },
                                        {
                                            "pro":"电饭煲","shows":"../../../static/img/itemLi51-11.png"
                                        },
                                        {
                                            "pro":"电饭煲","shows":"../../../static/img/itemLi51-11.png"
                                        },
                                        {
                                            "pro":"电饭煲","shows":"../../../static/img/itemLi51-11.png"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "id":6,
                            "name":"家装",
                            "pic":"../../../static/img/item6.jpg",
                            "item":[
                                {
                                    "itemName":"家装",
                                    "product":[
                                        {
                                            "pro":"客厅","shows":"../../../static/img/itemLi61-11.png"
                                        },
                                        {
                                            "pro":"客厅","shows":"../../../static/img/itemLi61-11.png"
                                        },
                                        {
                                            "pro":"客厅","shows":"../../../static/img/itemLi61-11.png"
                                        },
                                        {
                                            "pro":"客厅","shows":"../../../static/img/itemLi61-11.png"
                                        },
                                        {
                                            "pro":"客厅","shows":"../../../static/img/itemLi61-11.png"
                                        },
                                        {
                                            "pro":"客厅","shows":"../../../static/img/itemLi61-11.png"
                                        },
                                        {
                                            "pro":"客厅","shows":"../../../static/img/itemLi61-11.png"
                                        },
                                        {
                                            "pro":"客厅","shows":"../../../static/img/itemLi61-11.png"
                                        },
                                        {
                                            "pro":"客厅","shows":"../../../static/img/itemLi61-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":7,
                            "name":"路由",
                            "pic":"../../../static/img/item7.jpg",
                            "item":[
                                {
                                    "itemName":"路由",
                                    "product":[
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        },
                                        {
                                            "pro":"路由器4Q","shows":"../../../static/img/itemLi71-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":8,
                            "name":"智能",
                            "pic":"../../../static/img/item8.jpg",
                            "item":[
                                {
                                    "itemName":"智能",
                                    "product":[
                                        {
                                            "pro":"剃须刀","shows":"../../../static/img/itemLi81-11.png"
                                        },
                                        {
                                            "pro":"剃须刀","shows":"../../../static/img/itemLi81-11.png"
                                        },
                                        {
                                            "pro":"剃须刀","shows":"../../../static/img/itemLi81-11.png"
                                        },
                                        {
                                            "pro":"剃须刀","shows":"../../../static/img/itemLi81-11.png"
                                        },
                                        {
                                            "pro":"剃须刀","shows":"../../../static/img/itemLi81-11.png"
                                        },
                                        {
                                            "pro":"剃须刀","shows":"../../../static/img/itemLi81-11.png"
                                        }
                                    ],
                                    "botPic":"../../../static/img/item_more8.jpg"
                                },
                                {
                                    "itemName":"健康",
                                    "product":[
                                        {
                                            "pro":"手环","shows":"../../../static/img/itemLi82-11.png"
                                        },
                                        {
                                            "pro":"手环","shows":"../../../static/img/itemLi82-11.png"
                                        },
                                        {
                                            "pro":"手环","shows":"../../../static/img/itemLi82-11.png"
                                        },
                                        {
                                            "pro":"手环","shows":"../../../static/img/itemLi82-11.png"
                                        }
                                    ],
                                },
                                {
                                    "itemName":"户外",
                                    "product":[
                                        {
                                            "pro":"出行","shows":"../../../static/img/itemLi83-11.png"
                                        },
                                        {
                                            "pro":"出行","shows":"../../../static/img/itemLi83-11.png"
                                        },
                                        {
                                            "pro":"出行","shows":"../../../static/img/itemLi83-11.png"
                                        },
                                        {
                                            "pro":"出行","shows":"../../../static/img/itemLi83-11.png"
                                        },
                                        {
                                            "pro":"出行","shows":"../../../static/img/itemLi83-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":9,
                            "name":"儿童",
                            "pic":"../../../static/img/item9.jpg",
                            "item":[
                                {
                                    "itemName":"儿童",
                                    "product":[
                                        {
                                            "pro":"米兔儿童滑板车","shows":"../../../static/img/itemLi91-11.png"
                                        },
                                        {
                                            "pro":"米兔儿童滑板车","shows":"../../../static/img/itemLi91-11.png"
                                        },
                                        {
                                            "pro":"米兔儿童滑板车","shows":"../../../static/img/itemLi91-11.png"
                                        },
                                        {
                                            "pro":"米兔儿童滑板车","shows":"../../../static/img/itemLi91-11.png"
                                        },
                                        {
                                            "pro":"米兔儿童滑板车","shows":"../../../static/img/itemLi91-11.png"
                                        },
                                        {
                                            "pro":"米兔儿童滑板车","shows":"../../../static/img/itemLi91-11.png"
                                        },
                                        {
                                            "pro":"米兔儿童滑板车","shows":"../../../static/img/itemLi91-11.png"
                                        },
                                        {
                                            "pro":"米兔儿童滑板车","shows":"../../../static/img/itemLi91-11.png"
                                        },
                                        {
                                            "pro":"米兔儿童滑板车","shows":"../../../static/img/itemLi91-11.png"
                                        }
                                    ],
                                    "botPic":"../../../static/img/item_more3.jpg"
                                }
                            ]
                        },
                        {
                            "id":10,
                            "name":"灯具",
                            "pic":"../../../static/img/item10.jpg",
                            "item":[
                                {
                                    "itemName":"灯具",
                                    "product":[
                                        {
                                            "pro":"吸顶灯","shows":"../../../static/img/itemLi101-11.png"
                                        },
                                        {
                                            "pro":"吸顶灯","shows":"../../../static/img/itemLi101-11.png"
                                        },
                                        {
                                            "pro":"吸顶灯","shows":"../../../static/img/itemLi101-11.png"
                                        },
                                        {
                                            "pro":"吸顶灯","shows":"../../../static/img/itemLi101-11.png"
                                        },
                                        {
                                            "pro":"吸顶灯","shows":"../../../static/img/itemLi101-11.png"
                                        },
                                        {
                                            "pro":"吸顶灯","shows":"../../../static/img/itemLi101-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":11,
                            "name":"电源",
                            "pic":"../../../static/img/item11.jpg",
                            "item":[
                                {
                                    "itemName":"电源",
                                    "product":[
                                        {
                                            "pro":"插线板","shows":"../../../static/img/itemLi111-11.png"
                                        },
                                        {
                                            "pro":"插线板","shows":"../../../static/img/itemLi111-11.png"
                                        },
                                        {
                                            "pro":"插线板","shows":"../../../static/img/itemLi111-11.png"
                                        },
                                        {
                                            "pro":"插线板","shows":"../../../static/img/itemLi111-11.png"
                                        },
                                        {
                                            "pro":"插线板","shows":"../../../static/img/itemLi111-11.png"
                                        },
                                        {
                                            "pro":"插线板","shows":"../../../static/img/itemLi111-11.png"
                                        },
                                        {
                                            "pro":"插线板","shows":"../../../static/img/itemLi111-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":12,
                            "name":"耳机",
                            "pic":"../../../static/img/item12.jpg",
                            "item":[
                                {
                                    "itemName":"耳机",
                                    "product":[
                                        {
                                            "pro":"线控耳机","shows":"../../../static/img/itemLi121-11.png"
                                        },
                                        {
                                            "pro":"线控耳机","shows":"../../../static/img/itemLi121-11.png"
                                        },
                                        {
                                            "pro":"线控耳机","shows":"../../../static/img/itemLi121-11.png"
                                        },
                                        {
                                            "pro":"线控耳机","shows":"../../../static/img/itemLi121-11.png"
                                        },
                                        {
                                            "pro":"线控耳机","shows":"../../../static/img/itemLi121-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":13,
                            "name":"音箱",
                            "pic":"../../../static/img/item13.jpg",
                            "item":[
                                {
                                    "itemName":"音箱",
                                    "product":[
                                        {
                                            "pro":"小米小爱音箱mini","shows":"../../../static/img/itemLi131-11.png"
                                        },
                                        {
                                            "pro":"小米小爱音箱mini","shows":"../../../static/img/itemLi131-11.png"
                                        },
                                        {
                                            "pro":"小米小爱音箱mini","shows":"../../../static/img/itemLi131-11.png"
                                        },
                                        {
                                            "pro":"小米小爱音箱mini","shows":"../../../static/img/itemLi131-11.png"
                                        },
                                        {
                                            "pro":"小米小爱音箱mini","shows":"../../../static/img/itemLi131-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":14,
                            "name":"礼品",
                            "pic":"../../../static/img/item14.jpg",
                            "item":[
                                {
                                    "itemName":"礼品",
                                    "product":[
                                        {
                                            "pro":"送长辈","shows":"../../../static/img/itemLi141-11.png"
                                        },
                                        {
                                            "pro":"送长辈","shows":"../../../static/img/itemLi141-11.png"
                                        },
                                        {
                                            "pro":"送长辈","shows":"../../../static/img/itemLi141-11.png"
                                        },
                                        {
                                            "pro":"送长辈","shows":"../../../static/img/itemLi141-11.png"
                                        },
                                        {
                                            "pro":"送长辈","shows":"../../../static/img/itemLi141-11.png"
                                        },
                                        {
                                            "pro":"送长辈","shows":"../../../static/img/itemLi141-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":15,
                            "name":"生活",
                            "pic":"../../../static/img/item15.jpg",
                            "item":[
                                {
                                    "itemName":"生活",
                                    "product":[
                                        {
                                            "pro":"金米兔","shows":"../../../static/img/itemLi151-11.png"
                                        },
                                        {
                                            "pro":"金米兔","shows":"../../../static/img/itemLi151-11.png"
                                        },
                                        {
                                            "pro":"金米兔","shows":"../../../static/img/itemLi151-11.png"
                                        },
                                        {
                                            "pro":"金米兔","shows":"../../../static/img/itemLi151-11.png"
                                        },
                                        {
                                            "pro":"金米兔","shows":"../../../static/img/itemLi151-11.png"
                                        },
                                        {
                                            "pro":"金米兔","shows":"../../../static/img/itemLi151-11.png"
                                        },
                                        {
                                            "pro":"金米兔","shows":"../../../static/img/itemLi151-11.png"
                                        },
                                        {
                                            "pro":"金米兔","shows":"../../../static/img/itemLi151-11.png"
                                        },
                                        {
                                            "pro":"金米兔","shows":"../../../static/img/itemLi151-11.png"
                                        }
                                    ],
                                    "botPic":"../../../static/img/item_more15.jpg"
                                },
                                {
                                    "itemName":"居家",
                                    "product":[
                                        {
                                            "pro":"牙刷","shows":"../../../static/img/itemLi152-11.png"
                                        },
                                        {
                                            "pro":"牙刷","shows":"../../../static/img/itemLi152-11.png"
                                        },
                                        {
                                            "pro":"牙刷","shows":"../../../static/img/itemLi152-11.png"
                                        },
                                        {
                                            "pro":"牙刷","shows":"../../../static/img/itemLi152-11.png"
                                        },
                                        {
                                            "pro":"牙刷","shows":"../../../static/img/itemLi152-11.png"
                                        },
                                        {
                                            "pro":"牙刷","shows":"../../../static/img/itemLi152-11.png"
                                        },
                                        {
                                            "pro":"牙刷","shows":"../../../static/img/itemLi152-11.png"
                                        },
                                        {
                                            "pro":"牙刷","shows":"../../../static/img/itemLi152-11.png"
                                        },
                                        {
                                            "pro":"牙刷","shows":"../../../static/img/itemLi152-11.png"
                                        }
                                    ],
                                },
                                {
                                    "itemName":"文具",
                                    "product":[
                                        {
                                            "pro":"笔记本","shows":"../../../static/img/itemLi153-11.png"
                                        },
                                        {
                                            "pro":"笔记本","shows":"../../../static/img/itemLi153-11.png"
                                        },
                                        {
                                            "pro":"笔记本","shows":"../../../static/img/itemLi153-11.png"
                                        },
                                        {
                                            "pro":"笔记本","shows":"../../../static/img/itemLi153-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":16,
                            "name":"服务",
                            "pic":"../../../static/img/item16.jpg",
                            "item":[
                                {
                                    "itemName":"特色服务",
                                    "product":[
                                        {
                                            "pro":"手机保障服务","shows":"../../../static/img/itemLi161-11.png"
                                        },
                                        {
                                            "pro":"手机保障服务","shows":"../../../static/img/itemLi161-11.png"
                                        },
                                        {
                                            "pro":"手机保障服务","shows":"../../../static/img/itemLi161-11.png"
                                        },
                                        {
                                            "pro":"手机保障服务","shows":"../../../static/img/itemLi161-11.png"
                                        }
                                    ],
                                }
                            ]
                        },
                        {
                            "id":17,
                            "name":"米粉卡",
                            "item":[
                                {
                                    "itemName":"电话卡",
                                    "product":[
                                        {
                                            "pro":"服务卡","shows":"../../../static/img/itemLi171-11.png"
                                        },
                                        {
                                            "pro":"服务卡","shows":"../../../static/img/itemLi171-11.png"
                                        },
                                        {
                                            "pro":"服务卡","shows":"../../../static/img/itemLi171-11.png"
                                        },
                                        {
                                            "pro":"服务卡","shows":"../../../static/img/itemLi171-11.png"
                                        },
                                    ],
                                }
                            ]
                        },
                        {
                            "id":18,
                            "name":"零售店",
                            "item":[
                                {
                                    "itemName":"零售店",
                                    "product":[
                                        {
                                            "pro":"小米之家","shows":"../../../static/img/itemLi181-11.png"
                                        },
                                        {
                                            "pro":"小米之家","shows":"../../../static/img/itemLi181-11.png"
                                        },
                                        {
                                            "pro":"小米之家","shows":"../../../static/img/itemLi181-11.png"
                                        }
                                    ],
                                }
                            ]
                        }
                    ]
            }
        },
        components:{
            SortHeader,
            SortBody,
            SortFooter
        }
    }
</script>

<style lang="scss" scoped>
    .xmSort{
        height:100%;
        display: flex;
        flex-direction: column;
    }
</style>


